/* include/config.h.  Generated by configure.  */
/* include/config.h.in.  Generated automatically from configure.in by autoheader.  */

/* Define to empty if the keyword does not work.  */
/* #undef const */

/* Define if the setvbuf function takes the buffering type as its second
   argument and the buffer pointer as the third, as on System V
   before release 3.  */
/* #undef SETVBUF_REVERSED */

/* Define if you have the ANSI C header files.  */
#define STDC_HEADERS 1

/* Define if you have the gettimeofday function.  */
#define HAVE_GETTIMEOFDAY 1

/* Define if you have the popen function.  */
#define HAVE_POPEN 1

/* Define if you have the wcschr function.  */
#define HAVE_WCSCHR 1

/* Define if you have the wcsdup function.  */
#define HAVE_WCSDUP 1

/* Define if you have the <pam.h> header file.  */
/* #undef HAVE_PAM_H */

/* Define if you have the <pnm.h> header file.  */
/* #undef HAVE_PNM_H */

/* Define if you have the <unistd.h> header file.  */
#define HAVE_UNISTD_H 1

/* Define if you have the <wchar.h> header file.  */
#define HAVE_WCHAR_H 1
